// * This Java source file was generated by the Gradle 'init' task.

package inheritance;

public class Library {
    public static void main(String[] args) {
        Restaurant restaurant = new Restaurant("Delicious Meals", 4.5, "$$");
        System.out.println(restaurant.toString());

        Review review1 = new Review("Great food!", "Alice", 5);
        System.out.println(review1.toString());

        Review review2 = new Review("Average experience.", "Bob", 3);
        System.out.println(review2.toString());

        restaurant.addReview(review1);
        restaurant.addReview(review2);
        System.out.println(restaurant.toString());
    }
}
